### ISSUE TITLE
Gitpod default workpace and a fully functional gdal

### ISSUE THREAD

**Issue by maphew** [OSGeo/gdal#5442]
What recipe is needed to fire up the Gitpod default "workspace-full" image and have a fully functioning GDAL install within it?

_Refer to gitpod config in branch: https://github.com/maphew/gdal/tree/gitpod-for-gdal-gp-full_ and _comments originally posted by @zy6p in https://github.com/OSGeo/gdal/issues/5393#issuecomment-1060131368_

---
Nice try.
The [gitpod/workspace-full](https://github.com/gitpod-io/workspace-images) is its original image, so you don't have to set the image in the config entry `.gitpod.yml`. We just need to set up the run script as follows:

```yml
tasks:
  - name: Dependencies
    init: |
      sudo bash .github/workflows/ubuntu_20.04/build-deps.sh  # install deps
      sed "s/cd \/build/cd \/workspace\/gdal/1" -i .github/workflows/ubuntu_20.04/build.sh
      bash .github/workflows/ubuntu_20.04/build.sh. # build
```

The target build folder is not the same causing the error to be reported.

It seems inappropriate to package the source code when building the image, as the image is always updated slower than the source code. And gitpod has done something with its own mirrors, so when you open the same workspace multiple times, the files in the `workspace/${ProjectName}` directory will be preserved, while the rest of the directory will revert to the default. So there is no need to set up mirror and no need to clone the code manually.

There may still get some errors running build.sh, but this file is not built for gitpod, so it's understandable. But actually running build.sh is not particularly necessary, and we can run cmake successfully in ide.

---

When I try this recipe neither cmake nor the `build.sh` work out of the box.

Following https://github.com/maphew/gdal/blob/gitpod-for-gdal/CONTRIBUTING.md#setting-development-environment-cmake-experimental there are complaints that Python Numpy and Xerces are missing. I used the apt-get install lines from `ubuntu-small-latest.Dockerfile` to get farther but it evenutally fails with _CMake Error at cmake/helpers/CheckDependentLibraries.cmake:159 (message):
  Configured to use TILEDB, but not found_.

With `sudo bash .github/workflows/ubuntu_20.04/build.sh` it get's as far as _"configure: error: --with-kea argument is a not an executable file.  It should be the path to the kea_config script, often somewhere like /usr/local/bin/kea_config."_ before bailing out.

So what is missing to get either of these to work?
